# Generated by Django 4.2.6 on 2023-11-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mob_no',
            field=models.IntegerField(),
        ),
    ]
