# Generated by Django 4.0 on 2023-11-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='person',
            new_name='p',
        ),
    ]
