# Generated by Django 4.0 on 2023-11-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_person_profile_p'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='p',
            new_name='person',
        ),
    ]
