# Generated by Django 4.2.6 on 2023-11-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_p_profile_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fuel',
            },
        ),
        migrations.CreateModel(
            name='Cartype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fueltype', models.ManyToManyField(to='app.fueltype')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
